[2025-01-30T01:14:43.440+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T01:14:43.463+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.validade scheduled__2025-01-29T00:00:00+00:00 [queued]>
[2025-01-30T01:14:43.473+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.validade scheduled__2025-01-29T00:00:00+00:00 [queued]>
[2025-01-30T01:14:43.474+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T01:14:43.495+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): validade> on 2025-01-29 00:00:00+00:00
[2025-01-30T01:14:43.505+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=94) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T01:14:43.509+0000] {standard_task_runner.py:72} INFO - Started process 99 to run task
[2025-01-30T01:14:43.508+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'validade', 'scheduled__2025-01-29T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmp1stm_peq']
[2025-01-30T01:14:43.510+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask validade
[2025-01-30T01:14:43.844+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.validade scheduled__2025-01-29T00:00:00+00:00 [running]> on host 8fdf061243ba
[2025-01-30T01:14:43.964+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='validade' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-29T00:00:00+00:00'
[2025-01-30T01:14:43.966+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T01:14:43.967+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T01:14:43.967+0000] {logging_mixin.py:190} INFO - Current task name:validade state:running start_date:2025-01-30 01:14:43.463925+00:00
[2025-01-30T01:14:43.968+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-30T01:14:43.969+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T01:14:43.970+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-30T01:14:43.984+0000] {python.py:240} INFO - Done. Returned value was: invalido
[2025-01-30T01:14:43.984+0000] {branch.py:38} INFO - Branch into invalido
[2025-01-30T01:14:43.985+0000] {skipmixin.py:230} INFO - Following branch ('invalido',)
[2025-01-30T01:14:44.001+0000] {skipmixin.py:278} INFO - Skipping tasks [('copia', -1)]
[2025-01-30T01:14:44.043+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T01:14:44.044+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=validade, run_id=scheduled__2025-01-29T00:00:00+00:00, execution_date=20250129T000000, start_date=20250130T011443, end_date=20250130T011444
[2025-01-30T01:14:44.058+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T01:14:44.059+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T01:14:44.060+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-30 01:14:34.654323+00:00
[2025-01-30T01:14:44.060+0000] {logging_mixin.py:190} INFO - Task hostname:8fdf061243ba operator:BranchPythonOperator
[2025-01-30T01:14:44.086+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T01:14:44.287+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T01:14:44.293+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
