[2025-01-28T02:24:50.338+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:24:50.360+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.validade manual__2025-01-28T02:21:52.102766+00:00 [queued]>
[2025-01-28T02:24:50.371+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.validade manual__2025-01-28T02:21:52.102766+00:00 [queued]>
[2025-01-28T02:24:50.371+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-28T02:24:50.390+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): validade> on 2025-01-28 02:21:52.102766+00:00
[2025-01-28T02:24:50.403+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=305) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T02:24:50.413+0000] {standard_task_runner.py:72} INFO - Started process 309 to run task
[2025-01-28T02:24:50.413+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'validade', 'manual__2025-01-28T02:21:52.102766+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpf6ilh7fr']
[2025-01-28T02:24:50.415+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask validade
[2025-01-28T02:24:50.522+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.validade manual__2025-01-28T02:21:52.102766+00:00 [running]> on host 90d9eb5798dc
[2025-01-28T02:24:50.684+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='validade' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T02:21:52.102766+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T02:21:52.102766+00:00'
[2025-01-28T02:24:50.690+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T02:24:50.691+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T02:24:50.692+0000] {logging_mixin.py:190} INFO - Current task name:validade state:running start_date:2025-01-28 02:24:50.361642+00:00
[2025-01-28T02:24:50.692+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-28T02:24:50.693+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:24:50.714+0000] {python.py:240} INFO - Done. Returned value was: valido
[2025-01-28T02:24:50.754+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:24:50.755+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=validade, run_id=manual__2025-01-28T02:21:52.102766+00:00, execution_date=20250128T022152, start_date=20250128T022450, end_date=20250128T022450
[2025-01-28T02:24:50.769+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-28T02:24:50.770+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-28T02:24:50.772+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-28 02:24:45.090491+00:00
[2025-01-28T02:24:50.772+0000] {logging_mixin.py:190} INFO - Task hostname:90d9eb5798dc operator:PythonOperator
[2025-01-28T02:24:50.792+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:24:50.819+0000] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:24:50.824+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
