[2025-01-30T01:33:31.408+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T01:33:31.427+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.validar manual__2025-01-30T01:33:25.972330+00:00 [queued]>
[2025-01-30T01:33:31.436+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.validar manual__2025-01-30T01:33:25.972330+00:00 [queued]>
[2025-01-30T01:33:31.436+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T01:33:31.601+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): validar> on 2025-01-30 01:33:25.972330+00:00
[2025-01-30T01:33:31.610+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=434) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T01:33:31.611+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'validar', 'manual__2025-01-30T01:33:25.972330+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpssn84fy5']
[2025-01-30T01:33:31.612+0000] {standard_task_runner.py:72} INFO - Started process 436 to run task
[2025-01-30T01:33:31.613+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask validar
[2025-01-30T01:33:31.671+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.validar manual__2025-01-30T01:33:25.972330+00:00 [running]> on host 8fdf061243ba
[2025-01-30T01:33:31.772+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='validar' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T01:33:25.972330+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T01:33:25.972330+00:00'
[2025-01-30T01:33:31.773+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T01:33:31.774+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T01:33:31.774+0000] {logging_mixin.py:190} INFO - Current task name:validar state:running start_date:2025-01-30 01:33:31.428376+00:00
[2025-01-30T01:33:31.775+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-30T01:33:31.775+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T01:33:31.776+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-30T01:33:31.787+0000] {python.py:240} INFO - Done. Returned value was: copia
[2025-01-30T01:33:31.788+0000] {branch.py:38} INFO - Branch into copia
[2025-01-30T01:33:31.789+0000] {skipmixin.py:230} INFO - Following branch ('copia',)
[2025-01-30T01:33:31.800+0000] {skipmixin.py:278} INFO - Skipping tasks [('invalido', -1)]
[2025-01-30T01:33:31.840+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T01:33:31.840+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=validar, run_id=manual__2025-01-30T01:33:25.972330+00:00, execution_date=20250130T013325, start_date=20250130T013331, end_date=20250130T013331
[2025-01-30T01:33:31.852+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T01:33:31.853+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T01:33:31.853+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-30 01:33:25.988532+00:00
[2025-01-30T01:33:31.853+0000] {logging_mixin.py:190} INFO - Task hostname:8fdf061243ba operator:BranchPythonOperator
[2025-01-30T01:33:31.869+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T01:33:31.898+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T01:33:31.902+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
