[2025-01-28T02:24:54.373+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:24:54.404+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.invalido manual__2025-01-28T02:21:52.102766+00:00 [queued]>
[2025-01-28T02:24:54.420+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.invalido manual__2025-01-28T02:21:52.102766+00:00 [queued]>
[2025-01-28T02:24:54.421+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-28T02:24:54.446+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): invalido> on 2025-01-28 02:21:52.102766+00:00
[2025-01-28T02:24:54.458+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T02:24:54.460+0000] {standard_task_runner.py:72} INFO - Started process 322 to run task
[2025-01-28T02:24:54.460+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'invalido', 'manual__2025-01-28T02:21:52.102766+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpgpvj8u_6']
[2025-01-28T02:24:54.461+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask invalido
[2025-01-28T02:24:54.538+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.invalido manual__2025-01-28T02:21:52.102766+00:00 [running]> on host 90d9eb5798dc
[2025-01-28T02:24:54.973+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='invalido' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T02:21:52.102766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T02:21:52.102766+00:00'
[2025-01-28T02:24:54.975+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T02:24:54.976+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T02:24:54.977+0000] {logging_mixin.py:190} INFO - Current task name:invalido state:running start_date:2025-01-28 02:24:54.405518+00:00
[2025-01-28T02:24:54.977+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-28T02:24:54.978+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:24:54.979+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-28T02:24:54.981+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Error'"]
[2025-01-28T02:24:55.007+0000] {subprocess.py:99} INFO - Output:
[2025-01-28T02:24:55.009+0000] {subprocess.py:106} INFO - Error
[2025-01-28T02:24:55.010+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-28T02:24:55.048+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:24:55.049+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=invalido, run_id=manual__2025-01-28T02:21:52.102766+00:00, execution_date=20250128T022152, start_date=20250128T022454, end_date=20250128T022455
[2025-01-28T02:24:55.070+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-28T02:24:55.071+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-28T02:24:55.072+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-28 02:24:45.090491+00:00
[2025-01-28T02:24:55.072+0000] {logging_mixin.py:190} INFO - Task hostname:90d9eb5798dc operator:BashOperator
[2025-01-28T02:24:55.118+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:24:55.147+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:24:55.151+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
