[2025-01-29T18:14:24.534+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T18:14:24.559+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.validade manual__2025-01-29T18:14:18.454814+00:00 [queued]>
[2025-01-29T18:14:24.572+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.validade manual__2025-01-29T18:14:18.454814+00:00 [queued]>
[2025-01-29T18:14:24.573+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T18:14:24.597+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): validade> on 2025-01-29 18:14:18.454814+00:00
[2025-01-29T18:14:24.607+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T18:14:24.609+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2025-01-29T18:14:24.610+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'validade', 'manual__2025-01-29T18:14:18.454814+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmp2kpvol58']
[2025-01-29T18:14:24.612+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask validade
[2025-01-29T18:14:24.952+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.validade manual__2025-01-29T18:14:18.454814+00:00 [running]> on host 85767b30d73d
[2025-01-29T18:14:25.087+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='validade' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T18:14:18.454814+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T18:14:18.454814+00:00'
[2025-01-29T18:14:25.088+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-29T18:14:25.088+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-29T18:14:25.089+0000] {logging_mixin.py:190} INFO - Current task name:validade state:running start_date:2025-01-29 18:14:24.560420+00:00
[2025-01-29T18:14:25.089+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-29T18:14:25.090+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T18:14:25.090+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-29T18:14:25.104+0000] {python.py:240} INFO - Done. Returned value was: invalido
[2025-01-29T18:14:25.105+0000] {branch.py:38} INFO - Branch into invalido
[2025-01-29T18:14:25.105+0000] {skipmixin.py:230} INFO - Following branch ('invalido',)
[2025-01-29T18:14:25.126+0000] {skipmixin.py:278} INFO - Skipping tasks [('valido', -1)]
[2025-01-29T18:14:25.173+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T18:14:25.174+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=validade, run_id=manual__2025-01-29T18:14:18.454814+00:00, execution_date=20250129T181418, start_date=20250129T181424, end_date=20250129T181425
[2025-01-29T18:14:25.187+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-29T18:14:25.188+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-29T18:14:25.189+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-29 18:14:18.473522+00:00
[2025-01-29T18:14:25.189+0000] {logging_mixin.py:190} INFO - Task hostname:85767b30d73d operator:BranchPythonOperator
[2025-01-29T18:14:25.229+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T18:14:25.527+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-29T18:14:25.532+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
