[2025-01-28T02:28:25.951+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:28:25.970+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.validade manual__2025-01-28T02:24:48.799519+00:00 [queued]>
[2025-01-28T02:28:25.982+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.validade manual__2025-01-28T02:24:48.799519+00:00 [queued]>
[2025-01-28T02:28:25.983+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-28T02:28:26.000+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): validade> on 2025-01-28 02:24:48.799519+00:00
[2025-01-28T02:28:26.009+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=387) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T02:28:26.011+0000] {standard_task_runner.py:72} INFO - Started process 391 to run task
[2025-01-28T02:28:26.011+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'validade', 'manual__2025-01-28T02:24:48.799519+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmp_1hq9g51']
[2025-01-28T02:28:26.012+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask validade
[2025-01-28T02:28:26.062+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.validade manual__2025-01-28T02:24:48.799519+00:00 [running]> on host 90d9eb5798dc
[2025-01-28T02:28:26.183+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='validade' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T02:24:48.799519+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T02:24:48.799519+00:00'
[2025-01-28T02:28:26.185+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T02:28:26.186+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T02:28:26.187+0000] {logging_mixin.py:190} INFO - Current task name:validade state:running start_date:2025-01-28 02:28:25.971677+00:00
[2025-01-28T02:28:26.188+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-28T02:28:26.189+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:28:26.190+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-28T02:28:26.203+0000] {python.py:240} INFO - Done. Returned value was: valido
[2025-01-28T02:28:26.203+0000] {branch.py:38} INFO - Branch into valido
[2025-01-28T02:28:26.204+0000] {skipmixin.py:230} INFO - Following branch ('valido',)
[2025-01-28T02:28:26.218+0000] {skipmixin.py:278} INFO - Skipping tasks [('invalido', -1)]
[2025-01-28T02:28:26.442+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:28:26.443+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=validade, run_id=manual__2025-01-28T02:24:48.799519+00:00, execution_date=20250128T022448, start_date=20250128T022825, end_date=20250128T022826
[2025-01-28T02:28:26.454+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-28T02:28:26.455+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-28T02:28:26.455+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-28 02:28:14.171814+00:00
[2025-01-28T02:28:26.456+0000] {logging_mixin.py:190} INFO - Task hostname:90d9eb5798dc operator:BranchPythonOperator
[2025-01-28T02:28:26.507+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:28:26.535+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:28:26.539+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
