[2025-01-30T04:43:39.086+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T04:43:39.105+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa2_dag.validar manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:43:39.115+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa2_dag.validar manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:43:39.116+0000] {taskinstance.py:2866} INFO - Starting attempt 14 of 14
[2025-01-30T04:43:39.133+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): validar> on 2025-01-30 03:32:35.404173+00:00
[2025-01-30T04:43:39.142+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1526) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T04:43:39.143+0000] {standard_task_runner.py:72} INFO - Started process 1528 to run task
[2025-01-30T04:43:39.144+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa2_dag', 'validar', 'manual__2025-01-30T03:32:35.404173+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/etapa2_dag.py', '--cfg-path', '/tmp/tmpdvuk7r50']
[2025-01-30T04:43:39.145+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask validar
[2025-01-30T04:43:39.216+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa2_dag.validar manual__2025-01-30T03:32:35.404173+00:00 [running]> on host eed2ce10479b
[2025-01-30T04:43:39.393+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa2_dag' AIRFLOW_CTX_TASK_ID='validar' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T03:32:35.404173+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T03:32:35.404173+00:00'
[2025-01-30T04:43:39.395+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T04:43:39.396+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T04:43:39.397+0000] {logging_mixin.py:190} INFO - Current task name:validar state:running start_date:2025-01-30 04:43:39.106202+00:00
[2025-01-30T04:43:39.398+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag and current dag run status:running
[2025-01-30T04:43:39.399+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T04:43:39.400+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-30T04:43:39.418+0000] {python.py:240} INFO - Done. Returned value was: copia
[2025-01-30T04:43:39.419+0000] {branch.py:38} INFO - Branch into copia
[2025-01-30T04:43:39.420+0000] {skipmixin.py:230} INFO - Following branch ('copia',)
[2025-01-30T04:43:39.445+0000] {skipmixin.py:278} INFO - Skipping tasks [('invalido', -1)]
[2025-01-30T04:43:39.773+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T04:43:39.774+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa2_dag, task_id=validar, run_id=manual__2025-01-30T03:32:35.404173+00:00, execution_date=20250130T033235, start_date=20250130T044339, end_date=20250130T044339
[2025-01-30T04:43:39.789+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T04:43:39.789+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T04:43:39.790+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag queued_at:2025-01-30 04:43:34.048023+00:00
[2025-01-30T04:43:39.790+0000] {logging_mixin.py:190} INFO - Task hostname:eed2ce10479b operator:BranchPythonOperator
[2025-01-30T04:43:39.845+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T04:43:39.875+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T04:43:39.880+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
