[2025-01-30T04:37:56.401+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T04:37:56.424+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa2_dag.validar manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:37:56.438+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa2_dag.validar manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:37:56.439+0000] {taskinstance.py:2866} INFO - Starting attempt 11 of 11
[2025-01-30T04:37:56.458+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): validar> on 2025-01-30 03:32:35.404173+00:00
[2025-01-30T04:37:56.470+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa2_dag', 'validar', 'manual__2025-01-30T03:32:35.404173+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/etapa2_dag.py', '--cfg-path', '/tmp/tmpt05b0ezi']
[2025-01-30T04:37:56.469+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1369) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T04:37:56.472+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask validar
[2025-01-30T04:37:56.472+0000] {standard_task_runner.py:72} INFO - Started process 1371 to run task
[2025-01-30T04:37:56.527+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa2_dag.validar manual__2025-01-30T03:32:35.404173+00:00 [running]> on host eed2ce10479b
[2025-01-30T04:37:56.644+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa2_dag' AIRFLOW_CTX_TASK_ID='validar' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T03:32:35.404173+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T03:32:35.404173+00:00'
[2025-01-30T04:37:56.645+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T04:37:56.646+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T04:37:56.647+0000] {logging_mixin.py:190} INFO - Current task name:validar state:running start_date:2025-01-30 04:37:56.425161+00:00
[2025-01-30T04:37:56.648+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag and current dag run status:running
[2025-01-30T04:37:56.648+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T04:37:56.649+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-30T04:37:56.661+0000] {python.py:240} INFO - Done. Returned value was: copia
[2025-01-30T04:37:56.662+0000] {branch.py:38} INFO - Branch into copia
[2025-01-30T04:37:56.663+0000] {skipmixin.py:230} INFO - Following branch ('copia',)
[2025-01-30T04:37:56.680+0000] {skipmixin.py:278} INFO - Skipping tasks [('invalido', -1)]
[2025-01-30T04:37:56.779+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T04:37:56.780+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa2_dag, task_id=validar, run_id=manual__2025-01-30T03:32:35.404173+00:00, execution_date=20250130T033235, start_date=20250130T043756, end_date=20250130T043756
[2025-01-30T04:37:56.792+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T04:37:56.793+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T04:37:56.794+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag queued_at:2025-01-30 04:37:51.208049+00:00
[2025-01-30T04:37:56.794+0000] {logging_mixin.py:190} INFO - Task hostname:eed2ce10479b operator:BranchPythonOperator
[2025-01-30T04:37:56.848+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T04:37:56.886+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T04:37:56.891+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
