[2025-01-30T04:30:11.953+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T04:30:11.971+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa2_dag.validar manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:30:11.981+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa2_dag.validar manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:30:11.982+0000] {taskinstance.py:2866} INFO - Starting attempt 9 of 9
[2025-01-30T04:30:12.000+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): validar> on 2025-01-30 03:32:35.404173+00:00
[2025-01-30T04:30:12.010+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T04:30:12.012+0000] {standard_task_runner.py:72} INFO - Started process 1215 to run task
[2025-01-30T04:30:12.013+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa2_dag', 'validar', 'manual__2025-01-30T03:32:35.404173+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/etapa2_dag.py', '--cfg-path', '/tmp/tmptkwg419m']
[2025-01-30T04:30:12.014+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask validar
[2025-01-30T04:30:12.089+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa2_dag.validar manual__2025-01-30T03:32:35.404173+00:00 [running]> on host eed2ce10479b
[2025-01-30T04:30:12.191+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa2_dag' AIRFLOW_CTX_TASK_ID='validar' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T03:32:35.404173+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T03:32:35.404173+00:00'
[2025-01-30T04:30:12.192+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T04:30:12.193+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T04:30:12.193+0000] {logging_mixin.py:190} INFO - Current task name:validar state:running start_date:2025-01-30 04:30:11.972614+00:00
[2025-01-30T04:30:12.193+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag and current dag run status:running
[2025-01-30T04:30:12.194+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T04:30:12.194+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-30T04:30:12.205+0000] {python.py:240} INFO - Done. Returned value was: copia
[2025-01-30T04:30:12.206+0000] {branch.py:38} INFO - Branch into copia
[2025-01-30T04:30:12.207+0000] {skipmixin.py:230} INFO - Following branch ('copia',)
[2025-01-30T04:30:12.220+0000] {skipmixin.py:278} INFO - Skipping tasks [('invalido', -1)]
[2025-01-30T04:30:12.468+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T04:30:12.469+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa2_dag, task_id=validar, run_id=manual__2025-01-30T03:32:35.404173+00:00, execution_date=20250130T033235, start_date=20250130T043011, end_date=20250130T043012
[2025-01-30T04:30:12.481+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T04:30:12.482+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T04:30:12.482+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag queued_at:2025-01-30 04:30:05.293498+00:00
[2025-01-30T04:30:12.483+0000] {logging_mixin.py:190} INFO - Task hostname:eed2ce10479b operator:BranchPythonOperator
[2025-01-30T04:30:12.509+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T04:30:12.544+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T04:30:12.548+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
