[2025-01-30T01:18:23.203+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T01:18:23.229+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.invalido manual__2025-01-30T01:14:36.219663+00:00 [queued]>
[2025-01-30T01:18:23.242+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.invalido manual__2025-01-30T01:14:36.219663+00:00 [queued]>
[2025-01-30T01:18:23.243+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-30T01:18:23.407+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): invalido> on 2025-01-30 01:14:36.219663+00:00
[2025-01-30T01:18:23.416+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=173) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T01:18:23.418+0000] {standard_task_runner.py:72} INFO - Started process 177 to run task
[2025-01-30T01:18:23.418+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'invalido', 'manual__2025-01-30T01:14:36.219663+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpjm8y922y']
[2025-01-30T01:18:23.419+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask invalido
[2025-01-30T01:18:23.480+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.invalido manual__2025-01-30T01:14:36.219663+00:00 [running]> on host 8fdf061243ba
[2025-01-30T01:18:23.588+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='invalido' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T01:14:36.219663+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T01:14:36.219663+00:00'
[2025-01-30T01:18:23.590+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T01:18:23.590+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T01:18:23.591+0000] {logging_mixin.py:190} INFO - Current task name:invalido state:running start_date:2025-01-30 01:18:23.229927+00:00
[2025-01-30T01:18:23.591+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-30T01:18:23.592+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T01:18:23.592+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-30T01:18:23.594+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Error'"]
[2025-01-30T01:18:23.611+0000] {subprocess.py:99} INFO - Output:
[2025-01-30T01:18:23.613+0000] {subprocess.py:106} INFO - Error
[2025-01-30T01:18:23.613+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-30T01:18:23.642+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T01:18:23.643+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=invalido, run_id=manual__2025-01-30T01:14:36.219663+00:00, execution_date=20250130T011436, start_date=20250130T011823, end_date=20250130T011823
[2025-01-30T01:18:23.655+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T01:18:23.656+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T01:18:23.657+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-30 01:16:36.910739+00:00
[2025-01-30T01:18:23.657+0000] {logging_mixin.py:190} INFO - Task hostname:8fdf061243ba operator:BashOperator
[2025-01-30T01:18:23.673+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T01:18:23.691+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T01:18:23.696+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
