[2025-01-30T01:22:42.515+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T01:22:42.551+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.invalido manual__2025-01-30T01:22:34.572527+00:00 [queued]>
[2025-01-30T01:22:42.567+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.invalido manual__2025-01-30T01:22:34.572527+00:00 [queued]>
[2025-01-30T01:22:42.568+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T01:22:42.591+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): invalido> on 2025-01-30 01:22:34.572527+00:00
[2025-01-30T01:22:42.603+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T01:22:42.606+0000] {standard_task_runner.py:72} INFO - Started process 266 to run task
[2025-01-30T01:22:42.608+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'invalido', 'manual__2025-01-30T01:22:34.572527+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpb3kywgb6']
[2025-01-30T01:22:42.610+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask invalido
[2025-01-30T01:22:42.688+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.invalido manual__2025-01-30T01:22:34.572527+00:00 [running]> on host 8fdf061243ba
[2025-01-30T01:22:43.196+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='invalido' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T01:22:34.572527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T01:22:34.572527+00:00'
[2025-01-30T01:22:43.198+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T01:22:43.200+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T01:22:43.201+0000] {logging_mixin.py:190} INFO - Current task name:invalido state:running start_date:2025-01-30 01:22:42.552433+00:00
[2025-01-30T01:22:43.204+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-30T01:22:43.205+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T01:22:43.208+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-30T01:22:43.216+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Error'"]
[2025-01-30T01:22:43.249+0000] {subprocess.py:99} INFO - Output:
[2025-01-30T01:22:43.252+0000] {subprocess.py:106} INFO - Error
[2025-01-30T01:22:43.254+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-30T01:22:43.308+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T01:22:43.312+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=invalido, run_id=manual__2025-01-30T01:22:34.572527+00:00, execution_date=20250130T012234, start_date=20250130T012242, end_date=20250130T012243
[2025-01-30T01:22:43.339+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T01:22:43.340+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T01:22:43.341+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-30 01:22:34.591316+00:00
[2025-01-30T01:22:43.342+0000] {logging_mixin.py:190} INFO - Task hostname:8fdf061243ba operator:BashOperator
[2025-01-30T01:22:43.386+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T01:22:43.419+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T01:22:43.424+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
