[2025-01-30T02:27:45.561+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T02:27:45.580+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.validar manual__2025-01-30T02:27:39.702949+00:00 [queued]>
[2025-01-30T02:27:45.590+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.validar manual__2025-01-30T02:27:39.702949+00:00 [queued]>
[2025-01-30T02:27:45.590+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T02:27:45.748+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): validar> on 2025-01-30 02:27:39.702949+00:00
[2025-01-30T02:27:45.757+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T02:27:45.758+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2025-01-30T02:27:45.759+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'validar', 'manual__2025-01-30T02:27:39.702949+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmp6kf7u0sh']
[2025-01-30T02:27:45.760+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask validar
[2025-01-30T02:27:45.817+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.validar manual__2025-01-30T02:27:39.702949+00:00 [running]> on host 1899222f083d
[2025-01-30T02:27:45.921+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='validar' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T02:27:39.702949+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T02:27:39.702949+00:00'
[2025-01-30T02:27:45.922+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T02:27:45.923+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T02:27:45.923+0000] {logging_mixin.py:190} INFO - Current task name:validar state:running start_date:2025-01-30 02:27:45.580942+00:00
[2025-01-30T02:27:45.924+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-30T02:27:45.924+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T02:27:45.925+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-30T02:27:45.936+0000] {python.py:240} INFO - Done. Returned value was: copia
[2025-01-30T02:27:45.937+0000] {branch.py:38} INFO - Branch into copia
[2025-01-30T02:27:45.938+0000] {skipmixin.py:230} INFO - Following branch ('copia',)
[2025-01-30T02:27:45.952+0000] {skipmixin.py:278} INFO - Skipping tasks [('invalido', -1)]
[2025-01-30T02:27:45.999+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T02:27:46.000+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=validar, run_id=manual__2025-01-30T02:27:39.702949+00:00, execution_date=20250130T022739, start_date=20250130T022745, end_date=20250130T022746
[2025-01-30T02:27:46.014+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T02:27:46.014+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T02:27:46.015+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-30 02:27:39.712102+00:00
[2025-01-30T02:27:46.016+0000] {logging_mixin.py:190} INFO - Task hostname:1899222f083d operator:BranchPythonOperator
[2025-01-30T02:27:46.055+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T02:27:46.085+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T02:27:46.089+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
