[2025-01-30T02:33:10.970+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T02:33:10.994+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.copia manual__2025-01-30T02:27:39.702949+00:00 [queued]>
[2025-01-30T02:33:11.006+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.copia manual__2025-01-30T02:27:39.702949+00:00 [queued]>
[2025-01-30T02:33:11.007+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-30T02:33:11.175+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): copia> on 2025-01-30 02:27:39.702949+00:00
[2025-01-30T02:33:11.183+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=227) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T02:33:11.185+0000] {standard_task_runner.py:72} INFO - Started process 229 to run task
[2025-01-30T02:33:11.186+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'copia', 'manual__2025-01-30T02:27:39.702949+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpupps7h3m']
[2025-01-30T02:33:11.187+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask copia
[2025-01-30T02:33:11.241+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.copia manual__2025-01-30T02:27:39.702949+00:00 [running]> on host 1899222f083d
[2025-01-30T02:33:11.348+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='copia' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T02:27:39.702949+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T02:27:39.702949+00:00'
[2025-01-30T02:33:11.350+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T02:33:11.350+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T02:33:11.351+0000] {logging_mixin.py:190} INFO - Current task name:copia state:running start_date:2025-01-30 02:33:10.994960+00:00
[2025-01-30T02:33:11.351+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-30T02:33:11.352+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T02:33:11.442+0000] {logging_mixin.py:190} INFO - Erro durante a execução: This Connection is closed
[2025-01-30T02:33:11.443+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-30T02:33:11.458+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T02:33:11.459+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=copia, run_id=manual__2025-01-30T02:27:39.702949+00:00, execution_date=20250130T022739, start_date=20250130T023310, end_date=20250130T023311
[2025-01-30T02:33:11.474+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T02:33:11.475+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T02:33:11.476+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-30 02:33:01.895655+00:00
[2025-01-30T02:33:11.476+0000] {logging_mixin.py:190} INFO - Task hostname:1899222f083d operator:PythonOperator
[2025-01-30T02:33:11.521+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T02:33:11.540+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T02:33:11.544+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
